// Real tobacco data for all Indian States and Union Territories
// Source: Youth Tobacco Survey - GATS India

export interface StateDataRow {
  name: string
  area: "Total" | "Urban" | "Rural"
  everTobaccoUsers: number
  currentTobaccoUsers: number
  everTobaccoSmokers: number
  currentTobaccoSmokers: number
  everCigaretteUsers: number
  currentCigaretteUsers: number
  everBidiUsers: number
  currentBidiUsers: number
  everSmokelessUsers: number
  currentSmokelessUsers: number
  everPaanMasalaUsers: number
  susceptibleToFutureSmoking: number
  medianAgeCigarette: number
  medianAgeBidi: number
  medianAgeSmokeless: number
  awarenessECigarette: number
  everECigaretteUse: number
  quitSmokingLast12Months: number
  triedQuitSmoking: number
  wantedQuitSmoking: number
  quitSmokelessLast12Months: number
  triedQuitSmokeless: number
  wantedQuitSmokeless: number
  exposureAtHomeOrPublic: number
  exposureAtHome: number
  exposureEnclosedPublic: number
  exposureOutdoorPublic: number
  sawSmokingAtSchool: number
}

export const INDIA_STATES_DATA: StateDataRow[] = [
  // India Overall
  {
    name: "India",
    area: "Total",
    everTobaccoUsers: 18.1,
    currentTobaccoUsers: 8.5,
    everTobaccoSmokers: 11.0,
    currentTobaccoSmokers: 7.3,
    everCigaretteUsers: 4.6,
    currentCigaretteUsers: 2.6,
    everBidiUsers: 4.1,
    currentBidiUsers: 2.1,
    everSmokelessUsers: 12.5,
    currentSmokelessUsers: 4.1,
    everPaanMasalaUsers: 4.3,
    susceptibleToFutureSmoking: 8.4,
    medianAgeCigarette: 11.5,
    medianAgeBidi: 10.5,
    medianAgeSmokeless: 9.9,
    awarenessECigarette: 26.9,
    everECigaretteUse: 2.8,
    quitSmokingLast12Months: 10.6,
    triedQuitSmoking: 20.0,
    wantedQuitSmoking: 20.6,
    quitSmokelessLast12Months: 9.4,
    triedQuitSmokeless: 26.7,
    wantedQuitSmokeless: 24.8,
    exposureAtHomeOrPublic: 29.5,
    exposureAtHome: 11.2,
    exposureEnclosedPublic: 21.2,
    exposureOutdoorPublic: 23.4,
    sawSmokingAtSchool: 28.8,
  },
  {
    name: "India",
    area: "Urban",
    everTobaccoUsers: 13.5,
    currentTobaccoUsers: 5.5,
    everTobaccoSmokers: 8.1,
    currentTobaccoSmokers: 4.5,
    everCigaretteUsers: 4.1,
    currentCigaretteUsers: 2.3,
    everBidiUsers: 3.7,
    currentBidiUsers: 1.9,
    everSmokelessUsers: 8.5,
    currentSmokelessUsers: 2.1,
    everPaanMasalaUsers: 2.7,
    susceptibleToFutureSmoking: 6.8,
    medianAgeCigarette: 11.2,
    medianAgeBidi: 10.0,
    medianAgeSmokeless: 10.5,
    awarenessECigarette: 24.7,
    everECigaretteUse: 3.2,
    quitSmokingLast12Months: 14.6,
    triedQuitSmoking: 29.3,
    wantedQuitSmoking: 25.7,
    quitSmokelessLast12Months: 13.7,
    triedQuitSmokeless: 23.7,
    wantedQuitSmokeless: 24.0,
    exposureAtHomeOrPublic: 33.4,
    exposureAtHome: 9.0,
    exposureEnclosedPublic: 24.6,
    exposureOutdoorPublic: 26.8,
    sawSmokingAtSchool: 27.1,
  },
  {
    name: "India",
    area: "Rural",
    everTobaccoUsers: 19.5,
    currentTobaccoUsers: 9.4,
    everTobaccoSmokers: 11.8,
    currentTobaccoSmokers: 8.1,
    everCigaretteUsers: 4.7,
    currentCigaretteUsers: 2.6,
    everBidiUsers: 4.3,
    currentBidiUsers: 2.2,
    everSmokelessUsers: 13.7,
    currentSmokelessUsers: 4.6,
    everPaanMasalaUsers: 4.7,
    susceptibleToFutureSmoking: 8.9,
    medianAgeCigarette: 11.6,
    medianAgeBidi: 10.7,
    medianAgeSmokeless: 9.7,
    awarenessECigarette: 27.5,
    everECigaretteUse: 2.6,
    quitSmokingLast12Months: 9.8,
    triedQuitSmoking: 18.6,
    wantedQuitSmoking: 19.8,
    quitSmokelessLast12Months: 8.7,
    triedQuitSmokeless: 27.0,
    wantedQuitSmokeless: 24.9,
    exposureAtHomeOrPublic: 28.3,
    exposureAtHome: 11.8,
    exposureEnclosedPublic: 20.3,
    exposureOutdoorPublic: 22.5,
    sawSmokingAtSchool: 29.3,
  },

  // States and UTs
  {
    name: "Andaman and Nicobar Islands",
    area: "Total",
    everTobaccoUsers: 21.5,
    currentTobaccoUsers: 4.4,
    everTobaccoSmokers: 8.8,
    currentTobaccoSmokers: 3.7,
    everCigaretteUsers: 4.4,
    currentCigaretteUsers: 1.3,
    everBidiUsers: 2.7,
    currentBidiUsers: 1.0,
    everSmokelessUsers: 17.2,
    currentSmokelessUsers: 1.4,
    everPaanMasalaUsers: 7.1,
    susceptibleToFutureSmoking: 10.2,
    medianAgeCigarette: 12.0,
    medianAgeBidi: 12.3,
    medianAgeSmokeless: 11.4,
    awarenessECigarette: 13.6,
    everECigaretteUse: 1.6,
    quitSmokingLast12Months: 19.8,
    triedQuitSmoking: 32.9,
    wantedQuitSmoking: 30.9,
    quitSmokelessLast12Months: 4.6,
    triedQuitSmokeless: 16.3,
    wantedQuitSmokeless: 11.1,
    exposureAtHomeOrPublic: 35.6,
    exposureAtHome: 7.0,
    exposureEnclosedPublic: 26.9,
    exposureOutdoorPublic: 26.9,
    sawSmokingAtSchool: 29.0,
  },
  {
    name: "Andhra Pradesh",
    area: "Total",
    everTobaccoUsers: 7.3,
    currentTobaccoUsers: 2.6,
    everTobaccoSmokers: 4.4,
    currentTobaccoSmokers: 1.8,
    everCigaretteUsers: 2.6,
    currentCigaretteUsers: 1.1,
    everBidiUsers: 2.3,
    currentBidiUsers: 0.8,
    everSmokelessUsers: 4.4,
    currentSmokelessUsers: 1.1,
    everPaanMasalaUsers: 0.9,
    susceptibleToFutureSmoking: 4.1,
    medianAgeCigarette: 12.6,
    medianAgeBidi: 11.0,
    medianAgeSmokeless: 12.0,
    awarenessECigarette: 16.5,
    everECigaretteUse: 0.7,
    quitSmokingLast12Months: 12.8,
    triedQuitSmoking: 36.6,
    wantedQuitSmoking: 30.4,
    quitSmokelessLast12Months: 12.2,
    triedQuitSmokeless: 23.4,
    wantedQuitSmokeless: 36.5,
    exposureAtHomeOrPublic: 31.8,
    exposureAtHome: 7.2,
    exposureEnclosedPublic: 22.5,
    exposureOutdoorPublic: 25.0,
    sawSmokingAtSchool: 16.2,
  },
  {
    name: "Arunachal Pradesh",
    area: "Total",
    everTobaccoUsers: 63.1,
    currentTobaccoUsers: 57.9,
    everTobaccoSmokers: 59.2,
    currentTobaccoSmokers: 53.5,
    everCigaretteUsers: 47.9,
    currentCigaretteUsers: 45.9,
    everBidiUsers: 48.8,
    currentBidiUsers: 45.9,
    everSmokelessUsers: 41.7,
    currentSmokelessUsers: 40.7,
    everPaanMasalaUsers: 12.2,
    susceptibleToFutureSmoking: 25.6,
    medianAgeCigarette: 8.7,
    medianAgeBidi: 8.6,
    medianAgeSmokeless: 8.5,
    awarenessECigarette: 25.9,
    everECigaretteUse: 16.6,
    quitSmokingLast12Months: 22.6,
    triedQuitSmoking: 35.1,
    wantedQuitSmoking: 23.8,
    quitSmokelessLast12Months: 17.8,
    triedQuitSmokeless: 20.4,
    wantedQuitSmokeless: 16.8,
    exposureAtHomeOrPublic: 69.7,
    exposureAtHome: 31.4,
    exposureEnclosedPublic: 67.9,
    exposureOutdoorPublic: 64.1,
    sawSmokingAtSchool: 62.8,
  },
  {
    name: "Assam",
    area: "Total",
    everTobaccoUsers: 16.2,
    currentTobaccoUsers: 11.9,
    everTobaccoSmokers: 12.3,
    currentTobaccoSmokers: 10.5,
    everCigaretteUsers: 5.3,
    currentCigaretteUsers: 4.3,
    everBidiUsers: 3.4,
    currentBidiUsers: 2.9,
    everSmokelessUsers: 9.1,
    currentSmokelessUsers: 5.4,
    everPaanMasalaUsers: 3.3,
    susceptibleToFutureSmoking: 5.8,
    medianAgeCigarette: 10.9,
    medianAgeBidi: 9.5,
    medianAgeSmokeless: 10.7,
    awarenessECigarette: 28.6,
    everECigaretteUse: 4.2,
    quitSmokingLast12Months: 11.6,
    triedQuitSmoking: 14.9,
    wantedQuitSmoking: 22.9,
    quitSmokelessLast12Months: 20.0,
    triedQuitSmokeless: 20.0,
    wantedQuitSmokeless: 17.5,
    exposureAtHomeOrPublic: 26.0,
    exposureAtHome: 6.7,
    exposureEnclosedPublic: 19.1,
    exposureOutdoorPublic: 22.1,
    sawSmokingAtSchool: 19.7,
  },
  {
    name: "Bihar",
    area: "Total",
    everTobaccoUsers: 21.5,
    currentTobaccoUsers: 7.3,
    everTobaccoSmokers: 9.4,
    currentTobaccoSmokers: 4.7,
    everCigaretteUsers: 4.8,
    currentCigaretteUsers: 2.3,
    everBidiUsers: 3.3,
    currentBidiUsers: 1.8,
    everSmokelessUsers: 15.5,
    currentSmokelessUsers: 3.2,
    everPaanMasalaUsers: 1.1,
    susceptibleToFutureSmoking: 13.7,
    medianAgeCigarette: 7.9,
    medianAgeBidi: 8.5,
    medianAgeSmokeless: 7.0,
    awarenessECigarette: 39.3,
    everECigaretteUse: 2.0,
    quitSmokingLast12Months: 5.1,
    triedQuitSmoking: 23.6,
    wantedQuitSmoking: 28.9,
    quitSmokelessLast12Months: 1.5,
    triedQuitSmokeless: 12.4,
    wantedQuitSmokeless: 17.2,
    exposureAtHomeOrPublic: 18.4,
    exposureAtHome: 5.4,
    exposureEnclosedPublic: 14.3,
    exposureOutdoorPublic: 11.9,
    sawSmokingAtSchool: 26.1,
  },
  {
    name: "Chandigarh",
    area: "Total",
    everTobaccoUsers: 10.3,
    currentTobaccoUsers: 3.0,
    everTobaccoSmokers: 6.9,
    currentTobaccoSmokers: 2.5,
    everCigaretteUsers: 1.1,
    currentCigaretteUsers: 0.6,
    everBidiUsers: 3.2,
    currentBidiUsers: 0.6,
    everSmokelessUsers: 5.0,
    currentSmokelessUsers: 1.2,
    everPaanMasalaUsers: 1.3,
    susceptibleToFutureSmoking: 5.6,
    medianAgeCigarette: 9.5,
    medianAgeBidi: 8.4,
    medianAgeSmokeless: 10.2,
    awarenessECigarette: 24.8,
    everECigaretteUse: 2.5,
    quitSmokingLast12Months: 10.4,
    triedQuitSmoking: 22.6,
    wantedQuitSmoking: 13.4,
    quitSmokelessLast12Months: 5.7,
    triedQuitSmokeless: 12.1,
    wantedQuitSmokeless: 14.1,
    exposureAtHomeOrPublic: 28.2,
    exposureAtHome: 4.6,
    exposureEnclosedPublic: 15.8,
    exposureOutdoorPublic: 22.6,
    sawSmokingAtSchool: 21.9,
  },
  {
    name: "Chhattisgarh",
    area: "Total",
    everTobaccoUsers: 18.8,
    currentTobaccoUsers: 8.0,
    everTobaccoSmokers: 10.4,
    currentTobaccoSmokers: 6.9,
    everCigaretteUsers: 6.3,
    currentCigaretteUsers: 4.5,
    everBidiUsers: 4.2,
    currentBidiUsers: 2.2,
    everSmokelessUsers: 14.4,
    currentSmokelessUsers: 2.6,
    everPaanMasalaUsers: 2.7,
    susceptibleToFutureSmoking: 10.0,
    medianAgeCigarette: 8.2,
    medianAgeBidi: 9.1,
    medianAgeSmokeless: 7.3,
    awarenessECigarette: 20.6,
    everECigaretteUse: 2.1,
    quitSmokingLast12Months: 18.5,
    triedQuitSmoking: 23.1,
    wantedQuitSmoking: 29.0,
    quitSmokelessLast12Months: 23.7,
    triedQuitSmokeless: 37.7,
    wantedQuitSmokeless: 21.3,
    exposureAtHomeOrPublic: 36.8,
    exposureAtHome: 16.8,
    exposureEnclosedPublic: 25.6,
    exposureOutdoorPublic: 24.2,
    sawSmokingAtSchool: 27.8,
  },
  {
    name: "Dadra and Nagar Haveli",
    area: "Total",
    everTobaccoUsers: 15.3,
    currentTobaccoUsers: 2.4,
    everTobaccoSmokers: 4.6,
    currentTobaccoSmokers: 2.2,
    everCigaretteUsers: 1.7,
    currentCigaretteUsers: 1.1,
    everBidiUsers: 2.5,
    currentBidiUsers: 1.3,
    everSmokelessUsers: 12.4,
    currentSmokelessUsers: 0.7,
    everPaanMasalaUsers: 5.3,
    susceptibleToFutureSmoking: 4.2,
    medianAgeCigarette: 11.1,
    medianAgeBidi: 12.1,
    medianAgeSmokeless: 9.6,
    awarenessECigarette: 17.2,
    everECigaretteUse: 1.2,
    quitSmokingLast12Months: 22.3,
    triedQuitSmoking: 57.1,
    wantedQuitSmoking: 52.1,
    quitSmokelessLast12Months: 80.0,
    triedQuitSmokeless: 67.4,
    wantedQuitSmokeless: 65.2,
    exposureAtHomeOrPublic: 38.0,
    exposureAtHome: 6.5,
    exposureEnclosedPublic: 21.6,
    exposureOutdoorPublic: 30.8,
    sawSmokingAtSchool: 37.4,
  },
  {
    name: "Daman and Diu",
    area: "Total",
    everTobaccoUsers: 11.8,
    currentTobaccoUsers: 4.3,
    everTobaccoSmokers: 6.9,
    currentTobaccoSmokers: 3.4,
    everCigaretteUsers: 3.4,
    currentCigaretteUsers: 2.2,
    everBidiUsers: 3.5,
    currentBidiUsers: 2.1,
    everSmokelessUsers: 7.5,
    currentSmokelessUsers: 1.9,
    everPaanMasalaUsers: 2.6,
    susceptibleToFutureSmoking: 4.0,
    medianAgeCigarette: 12.3,
    medianAgeBidi: 9.8,
    medianAgeSmokeless: 9.6,
    awarenessECigarette: 26.2,
    everECigaretteUse: 1.5,
    quitSmokingLast12Months: 9.7,
    triedQuitSmoking: 28.6,
    wantedQuitSmoking: 29.7,
    quitSmokelessLast12Months: 27.4,
    triedQuitSmokeless: 24.0,
    wantedQuitSmokeless: 49.4,
    exposureAtHomeOrPublic: 28.2,
    exposureAtHome: 4.8,
    exposureEnclosedPublic: 19.1,
    exposureOutdoorPublic: 22.0,
    sawSmokingAtSchool: 28.8,
  },
  {
    name: "Delhi",
    area: "Total",
    everTobaccoUsers: 16.5,
    currentTobaccoUsers: 8.0,
    everTobaccoSmokers: 11.6,
    currentTobaccoSmokers: 7.5,
    everCigaretteUsers: 3.9,
    currentCigaretteUsers: 2.7,
    everBidiUsers: 3.0,
    currentBidiUsers: 2.5,
    everSmokelessUsers: 9.6,
    currentSmokelessUsers: 1.3,
    everPaanMasalaUsers: 4.2,
    susceptibleToFutureSmoking: 13.2,
    medianAgeCigarette: 7.8,
    medianAgeBidi: 8.0,
    medianAgeSmokeless: 11.6,
    awarenessECigarette: 40.6,
    everECigaretteUse: 11.1,
    quitSmokingLast12Months: 4.0,
    triedQuitSmoking: 30.0,
    wantedQuitSmoking: 11.4,
    quitSmokelessLast12Months: 9.6,
    triedQuitSmokeless: 14.1,
    wantedQuitSmokeless: 8.9,
    exposureAtHomeOrPublic: 37.8,
    exposureAtHome: 4.6,
    exposureEnclosedPublic: 31.6,
    exposureOutdoorPublic: 32.5,
    sawSmokingAtSchool: 27.6,
  },
  {
    name: "Goa",
    area: "Total",
    everTobaccoUsers: 9.3,
    currentTobaccoUsers: 2.1,
    everTobaccoSmokers: 5.3,
    currentTobaccoSmokers: 1.4,
    everCigaretteUsers: 2.7,
    currentCigaretteUsers: 0.7,
    everBidiUsers: 2.3,
    currentBidiUsers: 0.8,
    everSmokelessUsers: 5.6,
    currentSmokelessUsers: 0.9,
    everPaanMasalaUsers: 1.4,
    susceptibleToFutureSmoking: 6.2,
    medianAgeCigarette: 11.7,
    medianAgeBidi: 13.3,
    medianAgeSmokeless: 11.3,
    awarenessECigarette: 22.0,
    everECigaretteUse: 0.7,
    quitSmokingLast12Months: 7.7,
    triedQuitSmoking: 26.8,
    wantedQuitSmoking: 26.4,
    quitSmokelessLast12Months: 5.5,
    triedQuitSmokeless: 11.8,
    wantedQuitSmokeless: 31.0,
    exposureAtHomeOrPublic: 28.4,
    exposureAtHome: 2.8,
    exposureEnclosedPublic: 17.0,
    exposureOutdoorPublic: 23.0,
    sawSmokingAtSchool: 18.2,
  },
  {
    name: "Gujarat",
    area: "Total",
    everTobaccoUsers: 13.9,
    currentTobaccoUsers: 5.4,
    everTobaccoSmokers: 8.8,
    currentTobaccoSmokers: 5.1,
    everCigaretteUsers: 4.9,
    currentCigaretteUsers: 3.3,
    everBidiUsers: 5.8,
    currentBidiUsers: 3.3,
    everSmokelessUsers: 8.1,
    currentSmokelessUsers: 1.9,
    everPaanMasalaUsers: 3.4,
    susceptibleToFutureSmoking: 3.8,
    medianAgeCigarette: 10.8,
    medianAgeBidi: 9.4,
    medianAgeSmokeless: 9.9,
    awarenessECigarette: 21.6,
    everECigaretteUse: 2.0,
    quitSmokingLast12Months: 25.8,
    triedQuitSmoking: 63.0,
    wantedQuitSmoking: 57.1,
    quitSmokelessLast12Months: 68.6,
    triedQuitSmokeless: 40.2,
    wantedQuitSmokeless: 64.9,
    exposureAtHomeOrPublic: 29.8,
    exposureAtHome: 10.3,
    exposureEnclosedPublic: 20.6,
    exposureOutdoorPublic: 22.2,
    sawSmokingAtSchool: 34.4,
  },
  {
    name: "Haryana",
    area: "Total",
    everTobaccoUsers: 10.6,
    currentTobaccoUsers: 3.8,
    everTobaccoSmokers: 5.4,
    currentTobaccoSmokers: 2.7,
    everCigaretteUsers: 1.5,
    currentCigaretteUsers: 0.8,
    everBidiUsers: 1.9,
    currentBidiUsers: 0.7,
    everSmokelessUsers: 6.5,
    currentSmokelessUsers: 1.6,
    everPaanMasalaUsers: 2.6,
    susceptibleToFutureSmoking: 9.3,
    medianAgeCigarette: 11.8,
    medianAgeBidi: 9.5,
    medianAgeSmokeless: 7.7,
    awarenessECigarette: 31.0,
    everECigaretteUse: 2.2,
    quitSmokingLast12Months: 4.1,
    triedQuitSmoking: 19.1,
    wantedQuitSmoking: 19.2,
    quitSmokelessLast12Months: 2.2,
    triedQuitSmokeless: 10.7,
    wantedQuitSmokeless: 7.5,
    exposureAtHomeOrPublic: 23.7,
    exposureAtHome: 8.5,
    exposureEnclosedPublic: 14.4,
    exposureOutdoorPublic: 16.5,
    sawSmokingAtSchool: 24.5,
  },
  {
    name: "Himachal Pradesh",
    area: "Total",
    everTobaccoUsers: 33.4,
    currentTobaccoUsers: 1.0,
    everTobaccoSmokers: 5.5,
    currentTobaccoSmokers: 0.5,
    everCigaretteUsers: 1.3,
    currentCigaretteUsers: 0.1,
    everBidiUsers: 2.2,
    currentBidiUsers: 0.1,
    everSmokelessUsers: 30.6,
    currentSmokelessUsers: 0.5,
    everPaanMasalaUsers: 1.4,
    susceptibleToFutureSmoking: 7.1,
    medianAgeCigarette: 11.3,
    medianAgeBidi: 12.9,
    medianAgeSmokeless: 8.2,
    awarenessECigarette: 15.1,
    everECigaretteUse: 0.4,
    quitSmokingLast12Months: 1.1,
    triedQuitSmoking: 12.3,
    wantedQuitSmoking: 11.6,
    quitSmokelessLast12Months: 0.8,
    triedQuitSmokeless: 2.3,
    wantedQuitSmokeless: 0.0,
    exposureAtHomeOrPublic: 13.4,
    exposureAtHome: 4.5,
    exposureEnclosedPublic: 7.6,
    exposureOutdoorPublic: 9.1,
    sawSmokingAtSchool: 11.7,
  },
  {
    name: "Jammu and Kashmir",
    area: "Total",
    everTobaccoUsers: 12.5,
    currentTobaccoUsers: 6.2,
    everTobaccoSmokers: 8.4,
    currentTobaccoSmokers: 5.1,
    everCigaretteUsers: 5.2,
    currentCigaretteUsers: 3.4,
    everBidiUsers: 2.8,
    currentBidiUsers: 1.5,
    everSmokelessUsers: 7.8,
    currentSmokelessUsers: 2.4,
    everPaanMasalaUsers: 2.1,
    susceptibleToFutureSmoking: 6.5,
    medianAgeCigarette: 10.5,
    medianAgeBidi: 11.2,
    medianAgeSmokeless: 10.8,
    awarenessECigarette: 22.5,
    everECigaretteUse: 1.8,
    quitSmokingLast12Months: 12.4,
    triedQuitSmoking: 25.6,
    wantedQuitSmoking: 22.3,
    quitSmokelessLast12Months: 8.5,
    triedQuitSmokeless: 18.2,
    wantedQuitSmokeless: 15.6,
    exposureAtHomeOrPublic: 28.5,
    exposureAtHome: 8.2,
    exposureEnclosedPublic: 18.5,
    exposureOutdoorPublic: 20.4,
    sawSmokingAtSchool: 22.6,
  },
  {
    name: "Jharkhand",
    area: "Total",
    everTobaccoUsers: 24.6,
    currentTobaccoUsers: 5.1,
    everTobaccoSmokers: 9.0,
    currentTobaccoSmokers: 3.6,
    everCigaretteUsers: 3.7,
    currentCigaretteUsers: 1.1,
    everBidiUsers: 4.5,
    currentBidiUsers: 1.7,
    everSmokelessUsers: 20.1,
    currentSmokelessUsers: 2.7,
    everPaanMasalaUsers: 7.5,
    susceptibleToFutureSmoking: 6.2,
    medianAgeCigarette: 10.4,
    medianAgeBidi: 10.0,
    medianAgeSmokeless: 7.4,
    awarenessECigarette: 31.4,
    everECigaretteUse: 3.6,
    quitSmokingLast12Months: 11.1,
    triedQuitSmoking: 17.1,
    wantedQuitSmoking: 21.7,
    quitSmokelessLast12Months: 6.3,
    triedQuitSmokeless: 23.0,
    wantedQuitSmokeless: 20.5,
    exposureAtHomeOrPublic: 23.2,
    exposureAtHome: 6.8,
    exposureEnclosedPublic: 17.5,
    exposureOutdoorPublic: 19.7,
    sawSmokingAtSchool: 21.8,
  },
  {
    name: "Karnataka",
    area: "Total",
    everTobaccoUsers: 3.8,
    currentTobaccoUsers: 1.2,
    everTobaccoSmokers: 2.6,
    currentTobaccoSmokers: 0.5,
    everCigaretteUsers: 1.6,
    currentCigaretteUsers: 0.5,
    everBidiUsers: 1.0,
    currentBidiUsers: 0.5,
    everSmokelessUsers: 2.2,
    currentSmokelessUsers: 0.7,
    everPaanMasalaUsers: 0.5,
    susceptibleToFutureSmoking: 2.2,
    medianAgeCigarette: 11.5,
    medianAgeBidi: 12.5,
    medianAgeSmokeless: 12.1,
    awarenessECigarette: 21.4,
    everECigaretteUse: 0.0,
    quitSmokingLast12Months: 0.0,
    triedQuitSmoking: 99.9,
    wantedQuitSmoking: 99.9,
    quitSmokelessLast12Months: 0.0,
    triedQuitSmokeless: 0.0,
    wantedQuitSmokeless: 100.0,
    exposureAtHomeOrPublic: 28.7,
    exposureAtHome: 6.7,
    exposureEnclosedPublic: 16.4,
    exposureOutdoorPublic: 25.7,
    sawSmokingAtSchool: 13.7,
  },
  {
    name: "Kerala",
    area: "Total",
    everTobaccoUsers: 13.0,
    currentTobaccoUsers: 3.2,
    everTobaccoSmokers: 9.3,
    currentTobaccoSmokers: 2.4,
    everCigaretteUsers: 7.1,
    currentCigaretteUsers: 2.0,
    everBidiUsers: 4.8,
    currentBidiUsers: 0.9,
    everSmokelessUsers: 7.4,
    currentSmokelessUsers: 1.3,
    everPaanMasalaUsers: 0.8,
    susceptibleToFutureSmoking: 3.3,
    medianAgeCigarette: 11.9,
    medianAgeBidi: 11.9,
    medianAgeSmokeless: 11.5,
    awarenessECigarette: 41.0,
    everECigaretteUse: 2.1,
    quitSmokingLast12Months: 24.4,
    triedQuitSmoking: 56.6,
    wantedQuitSmoking: 38.9,
    quitSmokelessLast12Months: 11.6,
    triedQuitSmokeless: 34.4,
    wantedQuitSmokeless: 36.7,
    exposureAtHomeOrPublic: 34.2,
    exposureAtHome: 8.6,
    exposureEnclosedPublic: 20.7,
    exposureOutdoorPublic: 26.7,
    sawSmokingAtSchool: 14.2,
  },
  {
    name: "Lakshadweep",
    area: "Total",
    everTobaccoUsers: 23.3,
    currentTobaccoUsers: 8.1,
    everTobaccoSmokers: 13.4,
    currentTobaccoSmokers: 6.6,
    everCigaretteUsers: 8.4,
    currentCigaretteUsers: 4.0,
    everBidiUsers: 7.0,
    currentBidiUsers: 2.9,
    everSmokelessUsers: 15.7,
    currentSmokelessUsers: 3.3,
    everPaanMasalaUsers: 2.9,
    susceptibleToFutureSmoking: 4.3,
    medianAgeCigarette: 12.6,
    medianAgeBidi: 12.4,
    medianAgeSmokeless: 12.5,
    awarenessECigarette: 37.9,
    everECigaretteUse: 2.9,
    quitSmokingLast12Months: 35.2,
    triedQuitSmoking: 47.7,
    wantedQuitSmoking: 36.1,
    quitSmokelessLast12Months: 10.8,
    triedQuitSmokeless: 39.0,
    wantedQuitSmokeless: 30.9,
    exposureAtHomeOrPublic: 43.1,
    exposureAtHome: 21.0,
    exposureEnclosedPublic: 24.9,
    exposureOutdoorPublic: 32.5,
    sawSmokingAtSchool: 31.5,
  },
  {
    name: "Madhya Pradesh",
    area: "Total",
    everTobaccoUsers: 10.3,
    currentTobaccoUsers: 3.9,
    everTobaccoSmokers: 5.9,
    currentTobaccoSmokers: 3.7,
    everCigaretteUsers: 2.4,
    currentCigaretteUsers: 2.2,
    everBidiUsers: 3.2,
    currentBidiUsers: 1.6,
    everSmokelessUsers: 6.9,
    currentSmokelessUsers: 1.1,
    everPaanMasalaUsers: 0.6,
    susceptibleToFutureSmoking: 7.4,
    medianAgeCigarette: 8.5,
    medianAgeBidi: 7.2,
    medianAgeSmokeless: 9.5,
    awarenessECigarette: 26.4,
    everECigaretteUse: 2.7,
    quitSmokingLast12Months: 8.9,
    triedQuitSmoking: 26.2,
    wantedQuitSmoking: 37.9,
    quitSmokelessLast12Months: 8.5,
    triedQuitSmokeless: 48.3,
    wantedQuitSmokeless: 30.9,
    exposureAtHomeOrPublic: 23.8,
    exposureAtHome: 11.0,
    exposureEnclosedPublic: 17.5,
    exposureOutdoorPublic: 18.4,
    sawSmokingAtSchool: 22.4,
  },
  {
    name: "Maharashtra",
    area: "Total",
    everTobaccoUsers: 16.4,
    currentTobaccoUsers: 5.1,
    everTobaccoSmokers: 7.7,
    currentTobaccoSmokers: 4.0,
    everCigaretteUsers: 3.1,
    currentCigaretteUsers: 1.4,
    everBidiUsers: 3.7,
    currentBidiUsers: 1.6,
    everSmokelessUsers: 11.9,
    currentSmokelessUsers: 2.4,
    everPaanMasalaUsers: 4.5,
    susceptibleToFutureSmoking: 7.6,
    medianAgeCigarette: 10.6,
    medianAgeBidi: 9.7,
    medianAgeSmokeless: 10.3,
    awarenessECigarette: 25.5,
    everECigaretteUse: 2.8,
    quitSmokingLast12Months: 12.6,
    triedQuitSmoking: 19.8,
    wantedQuitSmoking: 24.3,
    quitSmokelessLast12Months: 9.1,
    triedQuitSmokeless: 20.2,
    wantedQuitSmokeless: 15.7,
    exposureAtHomeOrPublic: 31.5,
    exposureAtHome: 7.8,
    exposureEnclosedPublic: 22.2,
    exposureOutdoorPublic: 23.7,
    sawSmokingAtSchool: 35.4,
  },
  {
    name: "Manipur",
    area: "Total",
    everTobaccoUsers: 41.0,
    currentTobaccoUsers: 19.5,
    everTobaccoSmokers: 22.4,
    currentTobaccoSmokers: 13.4,
    everCigaretteUsers: 17.0,
    currentCigaretteUsers: 7.3,
    everBidiUsers: 11.8,
    currentBidiUsers: 7.3,
    everSmokelessUsers: 34.6,
    currentSmokelessUsers: 12.8,
    everPaanMasalaUsers: 7.2,
    susceptibleToFutureSmoking: 1.6,
    medianAgeCigarette: 11.9,
    medianAgeBidi: 9.3,
    medianAgeSmokeless: 11.7,
    awarenessECigarette: 10.2,
    everECigaretteUse: 1.9,
    quitSmokingLast12Months: 22.3,
    triedQuitSmoking: 61.0,
    wantedQuitSmoking: 50.3,
    quitSmokelessLast12Months: 31.9,
    triedQuitSmokeless: 40.2,
    wantedQuitSmokeless: 43.8,
    exposureAtHomeOrPublic: 51.6,
    exposureAtHome: 22.5,
    exposureEnclosedPublic: 41.7,
    exposureOutdoorPublic: 41.7,
    sawSmokingAtSchool: 31.0,
  },
  {
    name: "Meghalaya",
    area: "Total",
    everTobaccoUsers: 47.0,
    currentTobaccoUsers: 33.6,
    everTobaccoSmokers: 35.4,
    currentTobaccoSmokers: 27.1,
    everCigaretteUsers: 25.1,
    currentCigaretteUsers: 19.2,
    everBidiUsers: 19.6,
    currentBidiUsers: 15.1,
    everSmokelessUsers: 37.6,
    currentSmokelessUsers: 23.3,
    everPaanMasalaUsers: 13.2,
    susceptibleToFutureSmoking: 4.7,
    medianAgeCigarette: 11.7,
    medianAgeBidi: 12.1,
    medianAgeSmokeless: 11.6,
    awarenessECigarette: 36.9,
    everECigaretteUse: 11.1,
    quitSmokingLast12Months: 35.5,
    triedQuitSmoking: 43.6,
    wantedQuitSmoking: 59.6,
    quitSmokelessLast12Months: 54.8,
    triedQuitSmokeless: 47.8,
    wantedQuitSmokeless: 66.8,
    exposureAtHomeOrPublic: 69.5,
    exposureAtHome: 38.5,
    exposureEnclosedPublic: 55.1,
    exposureOutdoorPublic: 61.3,
    sawSmokingAtSchool: 46.1,
  },
  {
    name: "Mizoram",
    area: "Total",
    everTobaccoUsers: 89.7,
    currentTobaccoUsers: 57.9,
    everTobaccoSmokers: 83.0,
    currentTobaccoSmokers: 43.6,
    everCigaretteUsers: 76.9,
    currentCigaretteUsers: 35.3,
    everBidiUsers: 19.7,
    currentBidiUsers: 4.6,
    everSmokelessUsers: 69.1,
    currentSmokelessUsers: 33.3,
    everPaanMasalaUsers: 17.7,
    susceptibleToFutureSmoking: 2.4,
    medianAgeCigarette: 11.1,
    medianAgeBidi: 11.5,
    medianAgeSmokeless: 10.1,
    awarenessECigarette: 37.9,
    everECigaretteUse: 21.1,
    quitSmokingLast12Months: 21.8,
    triedQuitSmoking: 52.3,
    wantedQuitSmoking: 52.7,
    quitSmokelessLast12Months: 22.4,
    triedQuitSmokeless: 59.3,
    wantedQuitSmokeless: 50.2,
    exposureAtHomeOrPublic: 64.8,
    exposureAtHome: 42.4,
    exposureEnclosedPublic: 50.7,
    exposureOutdoorPublic: 55.8,
    sawSmokingAtSchool: 68.6,
  },
  {
    name: "Nagaland",
    area: "Total",
    everTobaccoUsers: 68.3,
    currentTobaccoUsers: 42.6,
    everTobaccoSmokers: 42.7,
    currentTobaccoSmokers: 26.5,
    everCigaretteUsers: 36.4,
    currentCigaretteUsers: 20.4,
    everBidiUsers: 29.1,
    currentBidiUsers: 20.8,
    everSmokelessUsers: 62.9,
    currentSmokelessUsers: 35.1,
    everPaanMasalaUsers: 30.5,
    susceptibleToFutureSmoking: 12.2,
    medianAgeCigarette: 11.0,
    medianAgeBidi: 10.1,
    medianAgeSmokeless: 10.4,
    awarenessECigarette: 17.3,
    everECigaretteUse: 2.9,
    quitSmokingLast12Months: 13.5,
    triedQuitSmoking: 65.7,
    wantedQuitSmoking: 78.6,
    quitSmokelessLast12Months: 13.5,
    triedQuitSmokeless: 72.6,
    wantedQuitSmokeless: 85.1,
    exposureAtHomeOrPublic: 68.7,
    exposureAtHome: 28.3,
    exposureEnclosedPublic: 57.9,
    exposureOutdoorPublic: 54.4,
    sawSmokingAtSchool: 35.7,
  },
  {
    name: "Odisha",
    area: "Total",
    everTobaccoUsers: 17.9,
    currentTobaccoUsers: 6.2,
    everTobaccoSmokers: 11.5,
    currentTobaccoSmokers: 4.6,
    everCigaretteUsers: 4.8,
    currentCigaretteUsers: 1.6,
    everBidiUsers: 4.2,
    currentBidiUsers: 1.9,
    everSmokelessUsers: 10.2,
    currentSmokelessUsers: 2.4,
    everPaanMasalaUsers: 3.7,
    susceptibleToFutureSmoking: 13.9,
    medianAgeCigarette: 11.1,
    medianAgeBidi: 10.7,
    medianAgeSmokeless: 10.1,
    awarenessECigarette: 9.6,
    everECigaretteUse: 2.0,
    quitSmokingLast12Months: 11.6,
    triedQuitSmoking: 24.1,
    wantedQuitSmoking: 20.4,
    quitSmokelessLast12Months: 18.0,
    triedQuitSmokeless: 36.8,
    wantedQuitSmokeless: 17.3,
    exposureAtHomeOrPublic: 19.0,
    exposureAtHome: 5.0,
    exposureEnclosedPublic: 12.8,
    exposureOutdoorPublic: 13.6,
    sawSmokingAtSchool: 20.7,
  },
  {
    name: "Puducherry",
    area: "Total",
    everTobaccoUsers: 11.6,
    currentTobaccoUsers: 4.3,
    everTobaccoSmokers: 5.7,
    currentTobaccoSmokers: 2.8,
    everCigaretteUsers: 1.5,
    currentCigaretteUsers: 0.0,
    everBidiUsers: 0.1,
    currentBidiUsers: 0.0,
    everSmokelessUsers: 8.6,
    currentSmokelessUsers: 1.4,
    everPaanMasalaUsers: 4.2,
    susceptibleToFutureSmoking: 3.8,
    medianAgeCigarette: 14.5,
    medianAgeBidi: 12.2,
    medianAgeSmokeless: 7.0,
    awarenessECigarette: 12.5,
    everECigaretteUse: 0.2,
    quitSmokingLast12Months: 24.8,
    triedQuitSmoking: 0.1,
    wantedQuitSmoking: 0.1,
    quitSmokelessLast12Months: 0.1,
    triedQuitSmokeless: 0.1,
    wantedQuitSmokeless: 0.1,
    exposureAtHomeOrPublic: 49.2,
    exposureAtHome: 3.0,
    exposureEnclosedPublic: 42.0,
    exposureOutdoorPublic: 37.8,
    sawSmokingAtSchool: 17.9,
  },
  {
    name: "Punjab",
    area: "Total",
    everTobaccoUsers: 12.3,
    currentTobaccoUsers: 5.7,
    everTobaccoSmokers: 8.2,
    currentTobaccoSmokers: 5.3,
    everCigaretteUsers: 4.8,
    currentCigaretteUsers: 3.6,
    everBidiUsers: 3.7,
    currentBidiUsers: 2.9,
    everSmokelessUsers: 7.2,
    currentSmokelessUsers: 1.4,
    everPaanMasalaUsers: 1.6,
    susceptibleToFutureSmoking: 5.4,
    medianAgeCigarette: 7.9,
    medianAgeBidi: 8.0,
    medianAgeSmokeless: 7.6,
    awarenessECigarette: 21.6,
    everECigaretteUse: 2.1,
    quitSmokingLast12Months: 4.6,
    triedQuitSmoking: 20.7,
    wantedQuitSmoking: 36.8,
    quitSmokelessLast12Months: 11.6,
    triedQuitSmokeless: 21.3,
    wantedQuitSmokeless: 21.4,
    exposureAtHomeOrPublic: 15.2,
    exposureAtHome: 4.8,
    exposureEnclosedPublic: 10.4,
    exposureOutdoorPublic: 10.7,
    sawSmokingAtSchool: 16.1,
  },
  {
    name: "Rajasthan",
    area: "Total",
    everTobaccoUsers: 11.1,
    currentTobaccoUsers: 4.1,
    everTobaccoSmokers: 8.0,
    currentTobaccoSmokers: 3.9,
    everCigaretteUsers: 7.0,
    currentCigaretteUsers: 3.7,
    everBidiUsers: 4.5,
    currentBidiUsers: 3.6,
    everSmokelessUsers: 7.0,
    currentSmokelessUsers: 3.7,
    everPaanMasalaUsers: 2.8,
    susceptibleToFutureSmoking: 17.1,
    medianAgeCigarette: 13.4,
    medianAgeBidi: 14.2,
    medianAgeSmokeless: 7.6,
    awarenessECigarette: 15.6,
    everECigaretteUse: 0.4,
    quitSmokingLast12Months: 30.4,
    triedQuitSmoking: 88.9,
    wantedQuitSmoking: 88.9,
    quitSmokelessLast12Months: 17.8,
    triedQuitSmokeless: 33.4,
    wantedQuitSmokeless: 2.4,
    exposureAtHomeOrPublic: 19.2,
    exposureAtHome: 9.3,
    exposureEnclosedPublic: 12.7,
    exposureOutdoorPublic: 15.7,
    sawSmokingAtSchool: 30.4,
  },
  {
    name: "Sikkim",
    area: "Total",
    everTobaccoUsers: 41.8,
    currentTobaccoUsers: 24.6,
    everTobaccoSmokers: 31.7,
    currentTobaccoSmokers: 23.4,
    everCigaretteUsers: 27.0,
    currentCigaretteUsers: 19.4,
    everBidiUsers: 14.3,
    currentBidiUsers: 9.9,
    everSmokelessUsers: 33.5,
    currentSmokelessUsers: 10.7,
    everPaanMasalaUsers: 9.7,
    susceptibleToFutureSmoking: 5.8,
    medianAgeCigarette: 12.7,
    medianAgeBidi: 12.2,
    medianAgeSmokeless: 12.8,
    awarenessECigarette: 50.0,
    everECigaretteUse: 14.1,
    quitSmokingLast12Months: 37.2,
    triedQuitSmoking: 54.2,
    wantedQuitSmoking: 49.1,
    quitSmokelessLast12Months: 17.3,
    triedQuitSmokeless: 35.2,
    wantedQuitSmokeless: 55.2,
    exposureAtHomeOrPublic: 51.7,
    exposureAtHome: 19.0,
    exposureEnclosedPublic: 37.3,
    exposureOutdoorPublic: 41.8,
    sawSmokingAtSchool: 36.2,
  },
  {
    name: "Tamil Nadu",
    area: "Total",
    everTobaccoUsers: 14.1,
    currentTobaccoUsers: 4.8,
    everTobaccoSmokers: 7.8,
    currentTobaccoSmokers: 4.1,
    everCigaretteUsers: 3.9,
    currentCigaretteUsers: 2.3,
    everBidiUsers: 3.7,
    currentBidiUsers: 1.7,
    everSmokelessUsers: 9.1,
    currentSmokelessUsers: 1.6,
    everPaanMasalaUsers: 2.1,
    susceptibleToFutureSmoking: 8.8,
    medianAgeCigarette: 11.0,
    medianAgeBidi: 10.9,
    medianAgeSmokeless: 8.3,
    awarenessECigarette: 11.1,
    everECigaretteUse: 2.1,
    quitSmokingLast12Months: 16.4,
    triedQuitSmoking: 25.3,
    wantedQuitSmoking: 20.1,
    quitSmokelessLast12Months: 8.8,
    triedQuitSmokeless: 12.1,
    wantedQuitSmokeless: 16.5,
    exposureAtHomeOrPublic: 43.5,
    exposureAtHome: 14.5,
    exposureEnclosedPublic: 32.1,
    exposureOutdoorPublic: 34.6,
    sawSmokingAtSchool: 28.3,
  },
  {
    name: "Telangana",
    area: "Total",
    everTobaccoUsers: 9.4,
    currentTobaccoUsers: 5.2,
    everTobaccoSmokers: 6.9,
    currentTobaccoSmokers: 4.0,
    everCigaretteUsers: 3.8,
    currentCigaretteUsers: 2.5,
    everBidiUsers: 2.5,
    currentBidiUsers: 1.1,
    everSmokelessUsers: 3.9,
    currentSmokelessUsers: 1.9,
    everPaanMasalaUsers: 1.5,
    susceptibleToFutureSmoking: 7.9,
    medianAgeCigarette: 13.1,
    medianAgeBidi: 10.1,
    medianAgeSmokeless: 12.6,
    awarenessECigarette: 25.3,
    everECigaretteUse: 1.5,
    quitSmokingLast12Months: 15.7,
    triedQuitSmoking: 15.3,
    wantedQuitSmoking: 30.1,
    quitSmokelessLast12Months: 5.9,
    triedQuitSmokeless: 9.6,
    wantedQuitSmokeless: 48.9,
    exposureAtHomeOrPublic: 42.1,
    exposureAtHome: 11.4,
    exposureEnclosedPublic: 30.9,
    exposureOutdoorPublic: 32.3,
    sawSmokingAtSchool: 21.9,
  },
  {
    name: "Tripura",
    area: "Total",
    everTobaccoUsers: 22.6,
    currentTobaccoUsers: 7.6,
    everTobaccoSmokers: 10.5,
    currentTobaccoSmokers: 4.0,
    everCigaretteUsers: 5.6,
    currentCigaretteUsers: 2.7,
    everBidiUsers: 4.3,
    currentBidiUsers: 1.9,
    everSmokelessUsers: 19.7,
    currentSmokelessUsers: 5.0,
    everPaanMasalaUsers: 8.2,
    susceptibleToFutureSmoking: 5.9,
    medianAgeCigarette: 9.9,
    medianAgeBidi: 9.4,
    medianAgeSmokeless: 8.0,
    awarenessECigarette: 38.0,
    everECigaretteUse: 2.7,
    quitSmokingLast12Months: 12.7,
    triedQuitSmoking: 25.7,
    wantedQuitSmoking: 40.2,
    quitSmokelessLast12Months: 15.1,
    triedQuitSmokeless: 13.9,
    wantedQuitSmokeless: 22.5,
    exposureAtHomeOrPublic: 43.7,
    exposureAtHome: 17.0,
    exposureEnclosedPublic: 30.8,
    exposureOutdoorPublic: 35.8,
    sawSmokingAtSchool: 19.2,
  },
  {
    name: "Uttar Pradesh",
    area: "Total",
    everTobaccoUsers: 32.2,
    currentTobaccoUsers: 22.9,
    everTobaccoSmokers: 23.4,
    currentTobaccoSmokers: 21.2,
    everCigaretteUsers: 4.0,
    currentCigaretteUsers: 2.3,
    everBidiUsers: 4.6,
    currentBidiUsers: 1.9,
    everSmokelessUsers: 24.4,
    currentSmokelessUsers: 12.3,
    everPaanMasalaUsers: 12.5,
    susceptibleToFutureSmoking: 8.0,
    medianAgeCigarette: 9.6,
    medianAgeBidi: 7.9,
    medianAgeSmokeless: 7.7,
    awarenessECigarette: 34.3,
    everECigaretteUse: 5.0,
    quitSmokingLast12Months: 3.2,
    triedQuitSmoking: 4.3,
    wantedQuitSmoking: 4.0,
    quitSmokelessLast12Months: 1.8,
    triedQuitSmokeless: 26.6,
    wantedQuitSmokeless: 26.8,
    exposureAtHomeOrPublic: 26.7,
    exposureAtHome: 16.3,
    exposureEnclosedPublic: 21.7,
    exposureOutdoorPublic: 23.3,
    sawSmokingAtSchool: 43.8,
  },
  {
    name: "Uttarakhand",
    area: "Total",
    everTobaccoUsers: 31.4,
    currentTobaccoUsers: 18.5,
    everTobaccoSmokers: 26.6,
    currentTobaccoSmokers: 17.2,
    everCigaretteUsers: 13.2,
    currentCigaretteUsers: 7.3,
    everBidiUsers: 14.3,
    currentBidiUsers: 5.6,
    everSmokelessUsers: 10.3,
    currentSmokelessUsers: 2.6,
    everPaanMasalaUsers: 2.9,
    susceptibleToFutureSmoking: 11.2,
    medianAgeCigarette: 7.0,
    medianAgeBidi: 7.5,
    medianAgeSmokeless: 7.0,
    awarenessECigarette: 36.9,
    everECigaretteUse: 7.6,
    quitSmokingLast12Months: 14.1,
    triedQuitSmoking: 20.9,
    wantedQuitSmoking: 17.9,
    quitSmokelessLast12Months: 7.1,
    triedQuitSmokeless: 8.8,
    wantedQuitSmokeless: 1.6,
    exposureAtHomeOrPublic: 42.5,
    exposureAtHome: 11.9,
    exposureEnclosedPublic: 31.0,
    exposureOutdoorPublic: 30.2,
    sawSmokingAtSchool: 17.8,
  },
  {
    name: "West Bengal",
    area: "Total",
    everTobaccoUsers: 17.3,
    currentTobaccoUsers: 7.1,
    everTobaccoSmokers: 9.3,
    currentTobaccoSmokers: 5.2,
    everCigaretteUsers: 5.4,
    currentCigaretteUsers: 3.6,
    everBidiUsers: 5.5,
    currentBidiUsers: 2.9,
    everSmokelessUsers: 11.1,
    currentSmokelessUsers: 3.0,
    everPaanMasalaUsers: 3.8,
    susceptibleToFutureSmoking: 6.7,
    medianAgeCigarette: 12.6,
    medianAgeBidi: 12.7,
    medianAgeSmokeless: 12.3,
    awarenessECigarette: 32.3,
    everECigaretteUse: 2.0,
    quitSmokingLast12Months: 16.9,
    triedQuitSmoking: 37.9,
    wantedQuitSmoking: 40.1,
    quitSmokelessLast12Months: 11.9,
    triedQuitSmokeless: 15.5,
    wantedQuitSmokeless: 13.8,
    exposureAtHomeOrPublic: 55.1,
    exposureAtHome: 27.0,
    exposureEnclosedPublic: 38.9,
    exposureOutdoorPublic: 46.6,
    sawSmokingAtSchool: 33.4,
  },
]

// Get unique state names (excluding area breakdowns for dropdown)
export const getUniqueStates = () => {
  const stateNames = new Set<string>()
  INDIA_STATES_DATA.forEach((row) => {
    if (row.area === "Total") {
      stateNames.add(row.name)
    }
  })
  return Array.from(stateNames).filter((name) => name !== "India")
}

// Get state data by name
export const getStateData = (stateName: string) => {
  return INDIA_STATES_DATA.filter((row) => row.name === stateName)
}

// Get India overall data
export const getIndiaData = () => {
  return INDIA_STATES_DATA.filter((row) => row.name === "India")
}

// Calculate estimated users based on population (rough estimates)
const STATE_POPULATIONS: Record<string, number> = {
  India: 1400000000,
  "Uttar Pradesh": 230000000,
  Maharashtra: 123000000,
  Bihar: 122000000,
  "West Bengal": 100000000,
  "Madhya Pradesh": 85000000,
  "Tamil Nadu": 77000000,
  Rajasthan: 79000000,
  Karnataka: 67000000,
  Gujarat: 64000000,
  "Andhra Pradesh": 53000000,
  Odisha: 46000000,
  Telangana: 38000000,
  Kerala: 35000000,
  Jharkhand: 38000000,
  Assam: 35000000,
  Punjab: 30000000,
  Chhattisgarh: 29000000,
  Haryana: 29000000,
  Delhi: 20000000,
  "Jammu and Kashmir": 14000000,
  Uttarakhand: 11000000,
  "Himachal Pradesh": 7500000,
  Tripura: 4000000,
  Meghalaya: 3300000,
  Manipur: 3000000,
  Nagaland: 2200000,
  Goa: 1600000,
  "Arunachal Pradesh": 1600000,
  Puducherry: 1500000,
  Mizoram: 1200000,
  Chandigarh: 1200000,
  Sikkim: 700000,
  "Andaman and Nicobar Islands": 400000,
  "Dadra and Nagar Haveli": 600000,
  "Daman and Diu": 250000,
  Lakshadweep: 70000,
}

export const getEstimatedUsers = (stateName: string, prevalence: number) => {
  const population = STATE_POPULATIONS[stateName] || 1000000
  return Math.round((prevalence / 100) * population)
}

export const getEstimatedDeaths = (stateName: string, prevalence: number) => {
  // Rough estimate: ~1% of tobacco users die annually from tobacco-related causes
  const users = getEstimatedUsers(stateName, prevalence)
  return Math.round(users * 0.01)
}
